# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f779515748ebfd62c683591841404591ebdcb42fa306f1179d898d6910778d5707ae39bb082ba1ceba08bf9b308827859e1f242fd507800cd819f0ea4aac5a01

test:
  secret_key_base: 3c44f933aa14e5b854c158690cc61541b619a08c9e68302fa3837a792db8a9b738b7bfd5cd0fdbd523dcb750bcb6d26fa3e82dfea9aabc11739251fc965a717c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
